name: Performance tests
on:
  push:
    branches:
      - master
      - perf-testing

jobs:
  performance_tests:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CDK_DEFAULT_ACCOUNT: $${{ secrets.CDK_DEFAULT_ACCOUNT }}
      CDK_DEFAULT_REGION: 'us-west-2'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: cd perf-sdk
      - run: npm install -g aws-cdk
      - run: npm install -g typescript
      - run: cdk deploy --require-approval never
      - run: cdk destroy -f

