name: Performance tests
on:
  push:
    branches:
      - master
      - perf-testing

jobs:
  performance_tests:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
      CDK_DEFAULT_REGION: us-west-2
      AWS_REGION: us-west-2
    defaults:
      run:
        working-directory: ./perf-cdk
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g aws-cdk
      - run: npm install -g typescript
      - run: npm i
      - id: cdk_deploy
        run: |
        cdk deploy --require-approval never -O deploy-output.json
        "echo ::set-output name=host_ip::$(jq -r .PerfCdkStack.simpleinstance1output deploy-output.json)"
      - run: echo ${{ steps.cdk_deploy.outputs.host_ip }}
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ steps.cdk_deploy.outputs.host_ip }}
          username: ec2-user
          key: ${{ secrets.EC2_USER_KEY }}
          port: 22
          script: whoami
      - run: cdk destroy -f

